### ISSUE TITLE
Super Startrek

### ISSUE THREAD

**Issue by peterw8102** [RC2014Z80/RC2014#12]
Just got the basic rom image running on my breadboard Z80. The Nascom basic seems to have a hard line length limit of 72 characters. There are a number of lines in the Startrek programme that are longer than this so they get truncated. I've just started looking at the code and trying to remember my Basic from 30 years ago.

Before I was too much time, is this a real problem or am I seeing something weird on my setup?

**Comment by ghost** [comment]
Hi Peter

I hit something similar. According to this thread, the limit of 72 characters is part of some variants of basic:
https://groups.google.com/forum/#!msg/rc2014-z80/_wV9xVQQ5Uc/Oy6VIn76DgAJ 

Hope this reassures you that there is nothing weird in your setup!
