### ISSUE TITLE
Bad 24886009.BIN

### ISSUE THREAD

**Issue by mmicko** [RC2014Z80/RC2014#15]
File ROMs/Factory/24886009.BIN is bad rom image, it have error in 2nd byte. it is 0x00 there but it should be 0xC3. Can also be spotted by comparing 24006000.BIN and this file
Due to this it is impossible to use 32K basic. After I have changed this and wrote new eprom all is working as expected.

**Comment by feilipu** [comment]
Close with https://github.com/RC2014Z80/RC2014/commit/0ffeca194efee971f66d9b9fdc1bd17ed87cf023
