### ISSUE TITLE
Timer? Interrupt?

### ISSUE THREAD

**Issue by spth** [RC2014Z80/RC2014#17]
Is there an obvious way to measure how much time has passed? Having a quick look at documentation I noticed no timers in the design and no regular interrupt that could be used to implement a timer in software either.
What's the preferred way to do this on the RC2014, to e.g. implement the C clock() function?

**Comment by feilipu** [comment]
There is no standard timer possibility. There are community CTC Modules to be found though.

RomWBW and various CP/M-3 builds have integrated the CTC for interrupts and I2C RTC devices as a time of day option.

Systems on the Z180 have the PRT, of course. RomWBW and FreeRTOS use this method. As does z88dk on the SCZ180 and YAZ180 Targets.

**Comment by feilipu** [comment]
The z88dk HBIOS Target (the bios underlying RomWBW) also provides an API that I used to implement [time functions](https://github.com/z88dk/z88dk/tree/master/libsrc/_DEVELOPMENT/target/hbios/driver/time). This can also be used on RC2014, but it only works if optional hardware is provided. 🤷

**Comment by feilipu** [comment]
Think this is answered.
