### ISSUE TITLE
Unable to open list file "hexload.lst"

### ISSUE THREAD

**Issue by akalulyadurov** [RC2014Z80/RC2014#8]
I follow that instruction https://github.com/RC2014Z80/RC2014/tree/master/ROMs to compile ROMs folder.
but it doesn't compile and there is no any file 'hexload.lst' in the corresponding directory.

c:\RC2014-master\ROMs>make
make -C hexload/
make[1]: Entering directory 'c:/RC2014-master/ROMs/hexload'
zcc +z80 --no-crt -v -m @hexload.lst -o hexload
Unable to open list file "hexload.lst"
Makefile:7: recipe for target 'hexload__.bin' failed
make[1]: *** [hexload__.bin] Error 1
make[1]: Leaving directory 'c:/RC2014-master/ROMs/hexload'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2

c:\RC2014-master\ROMs\hexload>dir
 Volume in drive C has no label.
 Volume Serial Number is E884-E259

 Directory of c:\RC2014-master\ROMs\hexload

13.12.2017  23:16    <DIR>          .
13.12.2017  23:16    <DIR>          ..
23.11.2017  04:19             1 990 bin2bas.py
23.11.2017  04:19               354 bin2bas2.py
23.11.2017  04:19             3 001 hexload.asm
23.11.2017  04:19             1 963 hexload.bas
23.11.2017  04:19               426 hexload_map.asm
23.11.2017  04:19               266 Makefile
23.11.2017  04:19               299 slowprint.py
               7 File(s)          8 299 bytes
               2 Dir(s)  15 975 227 392 bytes free

**Comment by feilipu** [comment]
Just to comment that there have been some additional ROM based applications added to this [ROMs](https://github.com/RC2014Z80/RC2014/tree/master/ROMs) directory, so compiling in the root won't work, as the overall solution hasn't been maintained. You will need to go into each directory to do the instructions there.

The missing hexload.lst file is my issue. .lst files are in the .gitignore, so they need to be added manually and I neglected to do it. Oops.

**Comment by feilipu** [comment]
Added the missing file.
